### ISSUE TITLE
AWS issue

### ISSUE THREAD

**Issue by letaureau** [Lee-Kevin/IoTWebAPP#1]
![66792d06-1036-11e6-9def-8964bbc98b5a](https://cloud.githubusercontent.com/assets/9986923/15033879/c5c75522-123d-11e6-9041-0dde8cd2c3cf.PNG)

When running this example getting this error message.

**Comment by xneo1** [comment]
I cloned it today and after seeing the browser page it then fails with the same results(different node and npm versions)
node: v0.12.15
npm:v3.8.2

Then I update to node.js LTS (4.4.7) and npm:v3.10.3 but the problem remained.
I have seen that the error was reported also here: https://github.com/adcloud/node-aws/issues/5
any ideas how to fix it?

**Comment by Oxid2178** [comment]
I have the same Problem:

> GET/images/left_control.png 304 0.750 ms - -
>  GET /images/right_control.png 304 3.216 ms - -
>  C:\Users\Antonio\Documents\GitHub\IoTWebAPP\IoTWebDemo\a
>                         humidity_data = body.msg.humidity
>                                                                   ^
> TypeError: Cannot read property 'humidity' of undefined
>     at Request._callback (C:\Users\Antonio\Documents\GitHub\IoTWebAPP\IoTWebDemo\app.js:48:28)
>     at Request.self.callback (C:\Users\Antonio\Documents\GitHub\IoTWebAPP\IoTWebDemo\node_modules\request\request.js:198:22)
>     at emitTwo (events.js:106:13)
>     at Request.emit (events.js:191:7)
>     at Request.<anonymous> (C:\Users\Antonio\Documents\GitHub\IoTWebAPP\IoTWebDemo\node_modules\request\request.js:1082:10)
>     at emitOne (events.js:101:20)
>     at Request.emit (events.js:188:7)
>     at IncomingMessage.<anonymous> (C:\Users\Antonio\Documents\GitHub\IoTWebAPP\IoTWebDemo\node_modules\request\request.js:1009:12)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:185:7)
> 
> npm ERR! Windows_NT 10.0.10586
>  npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program     Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
>  npm ERR! node v6.3.0
>  npm ERR! npm  v3.10.3
>  npm ERR! code ELIFECYCLE
>  npm ERR! aws@0.0.0 start: `node ./bin/www`
>  npm ERR! Exit status 1
>  npm ERR!
>  npm ERR! Failed at the aws@0.0.0 start script 'node ./bin/www'.
>  npm ERR! Make sure you have the latest version of node.js and npm installed.
>  npm ERR! If you do, this is most likely a problem with the aws package,
>  npm ERR! not with npm itself.
>  npm ERR! Tell the author that this fails on your system:
>  npm ERR!     node ./bin/www
>  npm ERR! You can get information on how to open an issue for this project with:
>  npm ERR!     npm bugs aws
>  npm ERR! Or if that isn't available, you can get their info via:
>  npm ERR!     npm owner ls aws
>  npm ERR! There is likely additional logging output above.
>  npm ERR! Please include the following file with any support request:
>  npm ERR!     C:\Users\Antonio\Documents\GitHub\IoTWebAPP\IoTWebDemo\npm-debug.log

any suggestion please?

Thanks

**Comment by Oxid2178** [comment]
Read this [stackoverflow tag](http://stackoverflow.com/questions/38578041/request-data-over-https-dosnt-work-after-starting-npm-start-and-webapp-at-loc) for more infos...
